name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: clone
      run: if cd FunnyBoi; then git pull; else git clone --recurse-submodules https://github.com/Burfedd/FunnyBoi.git; fi
    - name: cmake
      run: cmake FunnyBoi/.
    - name: make
      run: make
    - name: run
      run: ./FunnyBoi/Funnyboi
