name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - run: cd ../../../../automation/FunnyBoi
    - run: git pull
    - run: cmake .
    - run: make
    - run: ./FunnyBoi/FunnyBoi
    
